version: "3.7"

services:
  api:
    container_name: poll_voting_api
    build: .
    ports:
      - "3333:3333"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  db:
    container_name: poll_voting_db
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: poll_voting
    volumes:
      - polls_pg_data:/bitnami/postgresql
  redis:
    container_name: poll_voting_redis
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=docker
    ports:
      - "6379:6379"
    volumes:
      - "polls_redis_data:/bitnami/redis/data"
volumes:
  polls_pg_data:
  polls_redis_data:
