# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.7"

      - name: Peer Deps
        run: go run github.com/steebchen/prisma-client-go generate

      - name: Dependencies
        run: go mod tidy

      - name: Build
        run: go build -v cmd/main.go

      - name: Test
        run: go test -v $(go list ./... | grep -v -e "_e2e_test.go")
